### ISSUE TITLE
Adding Validators throws exception 

### ISSUE THREAD

**Issue by monofone** [neos/form-builder#17]
Steps to reproduce:

    Add a form
    Insert an element
    Add a validator to the collecion

Expected result:
There should be no exception(Flashmessage) shown

Actual result:
After adding the validator an Exception is shown in the [Flashmessage](https://gist.github.com/monofone/334fdde0c6c0a597e18aa503a7991ec6#file-validator-add-exception-html), the validator is added but the UI is not in a consistent state.

Tested in the new UI with [FormNodeTypePostprocessor.php:32](https://github.com/neos/form-builder/blob/master/Classes/NodeType/FormNodeTypePostprocessor.php#L32)  uncommented

**Comment by lorenzulrich** [comment]
I can confirm this.

**Comment by klfman** [comment]
I can confirm this, too

**Comment by klfman** [comment]
The same happens when adding Options to Neos.Form.Builder:SingleSelectRadiobuttons

**Comment by bwaidelich** [comment]
Confirmed. This happens in the new UI only.

**Comment by bwaidelich** [comment]
FYI: The exception in question is this one:
```
No Fusion object found in path 
"default<Neos.Neos:Page>/.../<Neos.Form.Builder:NodeBasedForm>/firstPage<Neos.Form.Builder:FormPage.Definition>/elements<Neos.Form.Builder:NodeBasedElementCollection>/itemRenderer<Neos.Fusion:Case>/formElementTypeFromNodeType<Neos.Fusion:Matcher>/renderer<Neos.Form.Builder:NodeBasedFormElement>/element<Neos.Form.Builder:Section.Definition>/elements/__meta/process/overrideFromNode<Neos.Form.Builder:NodeBasedElementCollection>/itemRenderer<Neos.Fusion:Case>/formElementTypeFromNodeType<Neos.Fusion:Matcher>/renderer<Neos.Form.Builder:NodeBasedFormElement>/element<Neos.Form.Builder:SingleLineText.Definition>/c6038228-9971-0bef-684e-ec7b24d9003e" Please make sure to define one in your Fusion configuration.```

That is triggered by the `RenderContentOutOfBand` Feedback (in `renderContent()`)..


I need to dig further to find out how to circumvent this, but maybe some Fusion specialist already has a hint!?

**Comment by skurfuerst** [comment]
Hey,
this sounds pretty much like it can be fixed by https://github.com/neos/neos-ui/pull/1693 - could you add this PR and check if this fixes the issue? Unfortunately I have not so much time currently, so I can't really promise when in the next days I check out the form builder and test it.

All the best,
Sebastian

**Comment by skurfuerst** [comment]
Validated, and fixed by https://github.com/neos/neos-ui/pull/1693/commits/c57492f7db376045424c297ea88ad5f68301c33c

**Comment by bwaidelich** [comment]
@skurfuerst awesomatic, thank you!! <3

**Comment by bwaidelich** [comment]
FYI: I tried to confirm the fix without success: The exception still occurs with latest master of Neos.Neos.Ui – I might have a broken setup though, maybe someone else can test this again?

**Comment by klfman** [comment]
Tried to confirm the fix, too, the exception still occurs with latest master of Neos.Neos.Ui. All other packages are updated, too, using Neos 3.3

**Comment by skurfuerst** [comment]
@klfman @bwaidelich it is not yet merged (part of https://github.com/neos/neos-ui/pull/1693 )
